config/routes.rb
Wackypedia::Application.routes.draw do
  resources :services

  resources :articles, only: %i[new create show]
  root 'encyclopedia#index'
end

app/models/article.rb
class Article
  include ActiveModel::Model
  attr_accessor :id, :title, :body, :pubdate
  attr_writer :encyclopedia

  def encyclopedia
    @encyclopedia ||= THE_ENCYCLOPEDIA
  end

  def publish(clock = DateTime)
    return false unless valid?
    self.pubdate ||= clock.now
    @encyclopedia.add_entry(self)
  end
end

app/models/encyclopedia.rb
class Encyclopedia
  attr_reader :name

  def initialize(name: nil)
    @name = name
  end

  def self.model_name
    ActiveModel::Name.new(self)
  end

  def new_article(*args)
    article_source.call(*args).tap do |a|
      a.encyclopedia = self
    end
  end

  def entries
    ArticleStorageAdapter.fetch_all
  end

  def add_entry(entry)
    ArticleStorageAdapter.add(entry)
  end

  private

  def article_source
    @article_source ||= ArticleStorageAdapter.public_method(:new_article)
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def encyclopedia
    @encyclopedia ||= THE_ENCYCLOPEDIA
  end
  helper_method :encyclopedia
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html, :json

  def new
    @article = encyclopedia.new_article
  end

  def create
    @article = encyclopedia.new_article(article_params)
    if @article.publish
      redirect_to root_path, notice: 'Article added!'
    else
      render 'new'
    end
  end

  def show
  end

  private

  attr_reader :article
  helper_method :article

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/encyclopedia_controller.rb
class EncyclopediaController < ApplicationController
  def index
    @entries = encyclopedia.entries
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html do
          redirect_to @service,
                      notice: 'Service was successfully created.'
        end
        format.json do
          render action: 'show', status: :created, location: @service
        end
      else
        format.html { render action: 'new' }
        format.json do
          render json: @service.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html do
          redirect_to @service, notice: 'Service was successfully updated.'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json do
          render json: @service.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :code, :price)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<%= simple_form_for article, html: { class: 'form-horizontal' } do |f| %>
<%= f.input :title %>
<%= f.input :body, as: :text, input_html: { rows: 10 } %>
<div class="form-actions">
  <%= f.button :submit, class: 'btn-primary' %>
  <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
</div>
<% end %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/encyclopedia/index.html.erb
<% content_for :title do %><%= encyclopedia.name %><% end %>

<%- @entries.each do |entry| -%>
<article>
  <header>
    <h1><%= entry.title %></h1>
  </header>
  <p><%= entry.body %></p>
</article>
<%- end -%>

<p><%= link_to 'New article', new_article_path, class: 'btn btn-primary' %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to t('navigation.home'), root_path %></li>
  <li><%= link_to t('navigation.about'), page_path('about') %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wackypedia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %><%= t('pages.about.title') %><% end %>
<h3>About the Website</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :code %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.code %></td>
        <td><%= service.price %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @service.code %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/visitors/new.html.erb
<%= content_for :title, t(:welcome) %>